- name: Upload to release
             uses: softprops/action-gh-release@v2
             with:
               files: |
                 w2m-*.tar.gz
                 w2m-*.tar.gz.sha256
               generate_release_notes: true
